/**
 * app/robots.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Production-ready robots.txt generated by Next.js file convention.
 *
 * Strategy:
 *  - Allow all well-behaved crawlers on public pages.
 *  - Block admin, dashboard, all auth routes, all API routes, and any
 *    KYC/upload/internal paths from being indexed.
 */

import type { MetadataRoute } from "next";
import { SITE } from "@/lib/seo";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      // ── Primary rule: allow public pages ──────────────────────────────
      {
        userAgent: "*",
        allow: [
          "/",
          "/about",
          "/investment-plans",
          "/how-it-works",
          "/faq",
          "/contact",
          "/privacy-policy",
          "/terms-and-conditions",
          "/support",
        ],
        disallow: [
          // Auth routes
          "/login",
          "/register",
          "/forgot-password",
          "/login/otp",

          // Dashboard & private user area
          "/dashboard/",

          // Admin console
          "/admin/",

          // All API routes
          "/api/",

          // Next.js internals
          "/_next/",
          "/_vercel/",

          // Misc private
          "/profile/",
          "/wallet/",
          "/withdraw/",
          "/kyc/",
          "/invest/",
          "/transactions/",
          "/profit-analytics/",
          "/my-investments/",
        ],
      },

      // ── Block known aggressive/unwanted bots completely ───────────────
      {
        userAgent: "GPTBot",
        disallow: ["/"],
      },
      {
        userAgent: "CCBot",
        disallow: ["/"],
      },
      {
        userAgent: "anthropic-ai",
        disallow: ["/"],
      },
      {
        userAgent: "Google-Extended",
        disallow: ["/"],
      },
    ],

    sitemap:   `${SITE.url}/sitemap.xml`,
    host:       SITE.url,
  };
}
